<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "crt_viewhelper"
 *
 * Auto generated by Extension Builder 2015-01-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Cretection: Viewhelper',
	'description' => '',
	'category' => 'misc',
	'author' => 'Jonathan Starck',
	'author_email' => 'support@cretection.eu',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);